# netlify.toml
[build]
  # เข้าไปทำงานในโฟลเดอร์ frontend
  base    = "frontend"
  # คำสั่ง build
  command = "npm install && npm run build"
  # โฟลเดอร์ที่ Netlify จะเอาไป Serve เป็น Static files
  publish = ".output/public"
  # โฟลเดอร์ที่ Netlify จะเอาไปเป็น Functions
  functions = ".output/server"

# ทุก request ให้วนไปที่ SSR function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
