[build]
  # ถ้าใน UI คุณตั้ง Base directory เป็น "frontend" แล้ว ก็ไม่ต้องระบุ base ใน toml อีก
  command = "npm install && npm run generate"
  # โฟลเดอร์ที่ Nuxt3 สร้างไฟล์ static มาให้ (nuxi generate)
  publish = "frontend/.output/public"

[functions]
  directory = ".output/server"     # ← เปลี่ยนจาก frontend/.output/server เป็น .output/server

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
