[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/.output/public"

[functions]
  directory = "frontend/.output/server"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
