# netlify.toml
[build]
  # ถ้า Netlify UI ตั้ง Base directory = "frontend" ไว้แล้ว ก็ไม่ต้องกำหนด base ใน toml
  # base      = "frontend"
  command   = "npm install && npm run build"
  publish   = "frontend/.output/public"
  functions = "frontend/.output/server"

# ถ้าคุณใช้ SSR ต้อง redirect ทุกหน้าไปที่ฟังก์ชัน server
[[redirects]]
  from    = "/*"
  to      = "/.netlify/functions/server"
  status  = 200
