[build]
  # บอก Netlify ว่า base directory คือ frontend (ถ้าไม่ตั้งใน UI ก็ให้ uncomment บรรทัดนี้)
  base      = "frontend"

  command   = "npm install && npm run build"
  publish   = ".output/public"       # <-- เอา “frontend/” ออก
  functions = ".output/server"       # <-- เอา “frontend/” ออก

[[redirects]]
  from    = "/*"
  to      = "/.netlify/functions/server"
  status  = 200
