[build]
  base    = "frontend"                  # ถ้า UI ไม่ได้ตั้ง Base ให้ใส่บรรทัดนี้
  command = "npm install && npm run generate"
  publish = ".output/public"   

[functions]
  directory = ".output/server"     # ← เปลี่ยนจาก frontend/.output/server เป็น .output/server

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
