# netlify.toml (วางที่ root ของ repo)
[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = ".output/public"       # ← เปลี่ยนจาก frontend/.output/public เป็น .output/public

[functions]
  directory = ".output/server"     # ← เปลี่ยนจาก frontend/.output/server เป็น .output/server

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
